### ISSUE TITLE
Add requirement.txt file

### ISSUE THREAD

**Issue by ns23** [ns23/ImageCompression#13]
Add requirement.txt file with below packages
pillow
piexif

Also, update readme file with help to install packages wit requirement.txt

`pip install -U -r requirements.txt`

**Comment by Roldans** [comment]
Hello, i want to help you with this issue, but  I think If we use requirements.txt with the version's numbers it will work better.
Can you send me your version of these packages?

**Comment by ns23** [comment]
@Roldans Thank you for showing interest in contributing to this project.
And you are right version number will work better.
Below are the versions of packages
`piexif==1.0.13 ,
Pillow==5.0.0
`
Please update the pull request accordingly.
